apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lasample1
  labels:
    app: nginx1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx:apline
        ports:
        - containerPort: 80
